# ============================================
# DATABASE
# ============================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hostel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Ayush@2005}

# ============================================
# HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CRITICAL FIX — prevents LazyInitializationException
spring.jpa.open-in-view=false
spring.jackson.serialization.fail-on-empty-beans=false

# ============================================
# SERVER
# ============================================
server.port=${SERVER_PORT:8080}

# ============================================
# JWT
# ============================================
jwt.secret=${JWT_SECRET:my-super-secret-key-my-super-secret-key-12345}
jwt.expiration=${JWT_EXPIRATION:3600000}

# ============================================
# FILE UPLOAD
# ============================================
file.upload-dir=${UPLOAD_DIR:uploads/complaint-images}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# ============================================
# SWAGGER
# ============================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# ============================================
# MAIL (Gmail SMTP)
# ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:manit.hostel.maintainance@gmail.com}
spring.mail.password=${MAIL_PASSWORD:husi aubl szkm kjvv}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
